name: Step 2, Commit a file


on:
  workflow_dispatch:
  push:
    branches:
      - new-branch


  contents: write

jobs:
  on_commit_a_file:
    name: On commit a file

    if: ${{ !github.event.repository.is_template }}

    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

  
      - name: Update to step 3
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
          branch_name: new-branch
