name: Step 4, Merge your pull request


on:
  workflow_dispatch:
  push:
    branches:
      - main


permissions:

  contents: write

jobs:
  on_merge_your_pull_request:
    name: On merge your pull request

    
    if: ${{ !github.event.repository.is_template }}

    
    runs-on: ubuntu-latest

    steps:
      # check out the repository to edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      # Update README 
      #  set STEP to X
      - name: Update to step X
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 4
          to_step: X
          branch_name: new-branch
